# Use: docker-compose run htabroker

version: '3'
services:
  pulsar:
    container_name: pulsar-standalone
    image: apachepulsar/pulsar-all:2.5.2
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    network_mode: host

  htabroker:
    container_name: htabroker
    image: htabroker
    network_mode: host
    #stdin_open: true
    #tty: true
    depends_on: [pulsar]
